<?php

use Drupal\node\Entity\Node;
use Drupal\menu_link_content\Entity\MenuLinkContent;

//generate list of nodes with auto path generate unchecked
function generate_url_alias_list(){
    $query = \Drupal::entityQuery('node')
        ->condition('status', 1); //published or not
    $nids = $query->execute();
    $result = array();
    foreach ($nids as $nid) {
        $node = \Drupal\node\Entity\Node::load($nid); 
        if($node->path->pathauto != 1){
            $result[] = array('nid'=>$nid, 'path'=>$node->path->alias);
        }
    }  
    define("BASE_DIR", dirname(__FILE__));
    $fp = fopen(BASE_DIR . '/response.json', 'w');
    fwrite($fp, json_encode($result));
    fclose($fp);
    echo 'COMPLETED!'  . PHP_EOL;
}

//insert removed custom url and save
function reinsert_custom_url_alias(){
    define("BASE_DIR", dirname(__FILE__));
    $nodes = json_decode(file_get_contents(BASE_DIR . '/response.json'), true);
    foreach($nodes as $node){
        $nodeToUpdate = \Drupal\node\Entity\Node::load($node['nid']); 
        $nodeToUpdate->path->alias = $node['path'];
        $nodeToUpdate->save();
        var_dump($node['nid'] . '-' . $node['path']);
    }
}